### ISSUE TITLE
libexplorer-v0.5.6-nif-2.16-aarch64-apple-darwin.so nif panic

### ISSUE THREAD

**Issue by mlineen** [elixir-explorer/explorer#573]
```
** (ErlangError) Erlang error: :nif_panicked
    (explorer 0.5.6) Explorer.PolarsBackend.Native.df_from_parquet("./foo.parquet", nil, nil, nil)
    (explorer 0.5.6) lib/explorer/polars_backend/data_frame.ex:183: Explorer.PolarsBackend.DataFrame.from_parquet/3
    (explorer 0.5.6) lib/explorer/data_frame.ex:546: Explorer.DataFrame.from_parquet!/2
```

With the attached parquet file, the NIF (libexplorer-v0.5.6-nif-2.16-aarch64-apple-darwin.so) panics on the following command: 

```
Explorer.DataFrame.from_parquet!("./foo.parquet")
```

Oddly, sometimes I'm able to load the file once or twice before generating a panic consistently.

However, inside a docker container `docker run -it --mount type=bind,source=$(pwd),destination=/app elixir bash` on the same machine running a different NIF (libexplorer-v0.5.6-nif-2.16-aarch64-unknown-linux-gnu.so), I'm not able to generate the same panic.

I've tested this on an Apple M1 running 12.6.3 and an Apple M2 running 13.3.1, both panic locally. Here's the M1 info elixir info:

```
% elixir --version
Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.14.3 (compiled with Erlang/OTP 25)
```

To generate the attached parquet, see below.

```
import pyarrow as pa
import pyarrow.parquet as parquet
from decimal import *

n_cols = 50
n_rows = 1

labels = []
data = []

for n in range(n_cols):
    label = f"COL_{n}"
    values = pa.array([Decimal('123.456') for row in range(n_rows)],
                      type=pa.decimal128(7, 3))

    labels.append(label)
    data.append(values)

table = pa.table(data, names=labels)
parquet.write_table(table, "foo.parquet")
```

[foo.parquet.gz](https://github.com/elixir-nx/explorer/files/11216464/foo.parquet.gz)

Full stacktrace below:

```
% env RUST_BACKTRACE=full mix run loader.exs
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Serstack backtrace:
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
Polars does not support decimal types so the 'Series' are read as Float64
   0:        0x10c0ca850 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41165bc928a6a061
   1:        0x10b205a90 - core::fmt::write::hc1381c8a8889ae59
   2:        0x10c0ab838 - std::io::Write::write_fmt::h597fe54d40a99bca
   3:        0x10c0cb8e8 - std::sys_common::backtrace::print::hffd3791d3c76c5bf
   4:        0x10c0cb548 - std::panicking::default_hook::{{closure}}::hdcf127fa35c85582
   5:        0x10c0cc438 - std::panicking::rust_panic_with_hook::h1f31579a116a5567
   6:        0x10c0cbfb4 - std::panicking::begin_panic_handler::{{closure}}::h91adc5c2252dfa41
   7:        0x10c0cbf24 - std::sys_common::backtrace::__rust_end_short_backtrace::h1ce4494cc6011cab
   8:        0x10c0cbf00 - _rust_begin_unwind
   9:        0x10c1bbd34 - core::panicking::panic_fmt::he9b8054d565a504b
  10:        0x10c0ca16c - std::io::stdio::_eprint::h9187fd89875e2b57
  11:        0x10b8d491c - polars_core::series::from::<impl polars_core::series::Series>::try_from_arrow_unchecked::h8b8cea77cd903b79
  12:        0x10b8da3a0 - polars_core::series::from::<impl core::convert::TryFrom<(&str,alloc::vec::Vec<alloc::boxed::Box<dyn arrow2::array::Array>>)> for polars_core::series::Series>::try_from::h985ade0f791c2562
  13:        0x10bbc6ab4 - polars_io::parquet::read_impl::column_idx_to_series::h02c849d4a0d86012
  14:        0x10bbf0104 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  15:        0x10bac7f1c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  16:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  17:        0x10bbb27ac - rayon_core::job::StackJob<L,F,R>::run_inline::h7aef4d5caab42138
  18:        0x10bac804c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  19:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  20:        0x10bac7f1c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  21:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  22:        0x10bac7f1c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  23:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  24:        0x10bbb20e0 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::hbfff6e380e8fcf1c
  25:        0x10c22cb7c - rayon_core::registry::WorkerThread::wait_until_cold::hb2be894f15dcf02b
  26:        0x10c044e4c - std::sys_common::backtrace::__rust_begin_short_backtrace::h3c2bb8835fc5c95e
  27:        0x10c048bf8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::haa7db99dc77153e2
  28:        0x10c0cd674 - std::sys::unix::thread::Thread::new::thread_start::h7b399846e2ac9979
  29:        0x1b33c026c - __pthread_deallocate
stack backtrace:
   0:        0x10c0ca850 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41165bc928a6a061
   1:        0x10b205a90 - core::fmt::write::hc1381c8a8889ae59
   2:        0x10c0ab838 - std::io::Write::write_fmt::h597fe54d40a99bca
   3:        0x10c0cb8e8 - std::sys_common::backtrace::print::hffd3791d3c76c5bf
   4:        0x10c0cb548 - std::panicking::default_hook::{{closure}}::hdcf127fa35c85582
   5:        0x10c0cc438 - std::panicking::rust_panic_with_hook::h1f31579a116a5567
   6:        0x10c0cbfb4 - std::panicking::begin_panic_handler::{{closure}}::h91adc5c2252dfa41
   7:        0x10c0cbf24 - std::sys_common::backtrace::__rust_end_short_backtrace::h1ce4494cc6011cab
   8:        0x10c0cbf00 - _rust_begin_unwind
   9:        0x10c1bbd34 - core::panicking::panic_fmt::he9b8054d565a504b
  10:        0x10c0ca16c - std::io::stdio::_eprint::h9187fd89875e2b57
  11:        0x10b8d491c - polars_core::series::from::<impl polars_core::series::Series>::try_from_arrow_unchecked::h8b8cea77cd903b79
  12:        0x10b8da3a0 - polars_core::series::from::<impl core::convert::TryFrom<(&str,alloc::vec::Vec<alloc::boxed::Box<dyn arrow2::array::Array>>)> for polars_core::series::Series>::try_from::h985ade0f791c2562
  13:        0x10bbc6ab4 - polars_io::parquet::read_impl::column_idx_to_series::h02c849d4a0d86012
  14:        0x10bbf0104 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  15:        0x10bbb27ac - rayon_core::job::StackJob<L,F,R>::run_inline::h7aef4d5caab42138
  16:        0x10bac804c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  17:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  18:        0x10bbb27ac - rayon_core::job::StackJob<L,F,R>::run_inline::h7aef4d5caab42138
  19:        0x10bac804c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  20:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  21:        0x10bbb20e0 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::hbfff6e380e8fcf1c
  22:        0x10c22cb7c - rayon_core::registry::WorkerThread::wait_until_cold::hb2be894f15dcf02b
  23:        0x10bac7fbc - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  24:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  25:        0x10bac7f1c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  26:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  27:        0x10bac7f1c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  28:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  29:        0x10baf1b34 - rayon::iter::ParallelIterator::collect::hb39e240975a07ebe
  30:        0x10bbb1d18 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h9fabedfa507a04eb
  31:        0x10c22cb7c - rayon_core::registry::WorkerThread::wait_until_cold::hb2be894f15dcf02b
  32:        0x10c044e4c - std::sys_common::backtrace::__rust_begin_short_backtrace::h3c2bb8835fc5c95e
  33:        0x10c048bf8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::haa7db99dc77153e2
  34:        0x10c0cd674 - std::sys::unix::thread::Thread::new::thread_start::h7b399846e2ac9979
  35:        0x1b33c026c - __pthread_deallocate
stack backtrace:
   0:        0x10c0ca850 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41165bc928a6a061
   1:        0x10b205a90 - core::fmt::write::hc1381c8a8889ae59
   2:        0x10c0ab838 - std::io::Write::write_fmt::h597fe54d40a99bca
   3:        0x10c0cb8e8 - std::sys_common::backtrace::print::hffd3791d3c76c5bf
   4:        0x10c0cb548 - std::panicking::default_hook::{{closure}}::hdcf127fa35c85582
   5:        0x10c0cc438 - std::panicking::rust_panic_with_hook::h1f31579a116a5567
   6:        0x10c0cbfb4 - std::panicking::begin_panic_handler::{{closure}}::h91adc5c2252dfa41
   7:        0x10c0cbf24 - std::sys_common::backtrace::__rust_end_short_backtrace::h1ce4494cc6011cab
   8:        0x10c0cbf00 - _rust_begin_unwind
   9:        0x10c1bbd34 - core::panicking::panic_fmt::he9b8054d565a504b
  10:        0x10c0ca16c - std::io::stdio::_eprint::h9187fd89875e2b57
  11:        0x10b8d491c - polars_core::series::from::<impl polars_core::series::Series>::try_from_arrow_unchecked::h8b8cea77cd903b79
  12:        0x10b8da3a0 - polars_core::series::from::<impl core::convert::TryFrom<(&str,alloc::vec::Vec<alloc::boxed::Box<dyn arrow2::array::Array>>)> for polars_core::series::Series>::try_from::h985ade0f791c2562
  13:        0x10bbc6ab4 - polars_io::parquet::read_impl::column_idx_to_series::h02c849d4a0d86012
  14:        0x10bbf0104 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  15:        0x10bac7f1c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  16:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  17:        0x10bac7f1c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  18:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  19:        0x10bbb20e0 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::hbfff6e380e8fcf1c
  20:        0x10c22cb7c - rayon_core::registry::WorkerThread::wait_until_cold::hb2be894f15dcf02b
  21:        0x10c044e4c - std::sys_common::backtrace::__rust_begin_short_backtrace::h3c2bb8835fc5c95e
  22:        0x10c048bf8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::haa7db99dc77153e2
  23:        0x10c0cd674 - std::sys::unix::thread::Thread::new::thread_start::h7b399846e2ac9979
  24:        0x1b33c026c - __pthread_deallocate
stack backtrace:
   0:        0x10c0ca850 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41165bc928a6a061
   1:        0x10b205a90 - core::fmt::write::hc1381c8a8889ae59
   2:        0x10c0ab838 - std::io::Write::write_fmt::h597fe54d40a99bca
   3:        0x10c0cb8e8 - std::sys_common::backtrace::print::hffd3791d3c76c5bf
   4:        0x10c0cb548 - std::panicking::default_hook::{{closure}}::hdcf127fa35c85582
   5:        0x10c0cc438 - std::panicking::rust_panic_with_hook::h1f31579a116a5567
   6:        0x10c0cbfb4 - std::panicking::begin_panic_handler::{{closure}}::h91adc5c2252dfa41
   7:        0x10c0cbf24 - std::sys_common::backtrace::__rust_end_short_backtrace::h1ce4494cc6011cab
   8:        0x10c0cbf00 - _rust_begin_unwind
   9:        0x10c1bbd34 - core::panicking::panic_fmt::he9b8054d565a504b
  10:        0x10c0ca16c - std::io::stdio::_eprint::h9187fd89875e2b57
  11:        0x10b8d491c - polars_core::series::from::<impl polars_core::series::Series>::try_from_arrow_unchecked::h8b8cea77cd903b79
  12:        0x10b8da3a0 - polars_core::series::from::<impl core::convert::TryFrom<(&str,alloc::vec::Vec<alloc::boxed::Box<dyn arrow2::array::Array>>)> for polars_core::series::Series>::try_from::h985ade0f791c2562
  13:        0x10bbc6ab4 - polars_io::parquet::read_impl::column_idx_to_series::h02c849d4a0d86012
  14:        0x10bbf0104 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  15:        0x10bbb27ac - rayon_core::job::StackJob<L,F,R>::run_inline::h7aef4d5caab42138
  16:        0x10bac804c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  17:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  18:        0x10bbb27ac - rayon_core::job::StackJob<L,F,R>::run_inline::h7aef4d5caab42138
  19:        0x10bac804c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  20:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  21:        0x10bbb27ac - rayon_core::job::StackJob<L,F,R>::run_inline::h7aef4d5caab42138
  22:        0x10bac804c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  23:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  24:        0x10bac7f1c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  25:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  26:        0x10bac7f1c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  27:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  28:        0x10bbb20e0 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::hbfff6e380e8fcf1c
  29:        0x10c22cb7c - rayon_core::registry::WorkerThread::wait_until_cold::hb2be894f15dcf02b
  30:        0x10c044e4c - std::sys_common::backtrace::__rust_begin_short_backtrace::h3c2bb8835fc5c95e
  31:        0x10c048bf8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::haa7db99dc77153e2
  32:        0x10c0cd674 - std::sys::unix::thread::Thread::new::thread_start::h7b399846e2ac9979
  33:        0x1b33c026c - __pthread_deallocate
stack backtrace:
   0:        0x10c0ca850 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41165bc928a6a061
   1:        0x10b205a90 - core::fmt::write::hc1381c8a8889ae59
   2:        0x10c0ab838 - std::io::Write::write_fmt::h597fe54d40a99bca
   3:        0x10c0cb8e8 - std::sys_common::backtrace::print::hffd3791d3c76c5bf
   4:        0x10c0cb548 - std::panicking::default_hook::{{closure}}::hdcf127fa35c85582
   5:        0x10c0cc438 - std::panicking::rust_panic_with_hook::h1f31579a116a5567
   6:        0x10c0cbfb4 - std::panicking::begin_panic_handler::{{closure}}::h91adc5c2252dfa41
   7:        0x10c0cbf24 - std::sys_common::backtrace::__rust_end_short_backtrace::h1ce4494cc6011cab
   8:        0x10c0cbf00 - _rust_begin_unwind
   9:        0x10c1bbd34 - core::panicking::panic_fmt::he9b8054d565a504b
  10:        0x10c0ca16c - std::io::stdio::_eprint::h9187fd89875e2b57
  11:        0x10b8d491c - polars_core::series::from::<impl polars_core::series::Series>::try_from_arrow_unchecked::h8b8cea77cd903b79
  12:        0x10b8da3a0 - polars_core::series::from::<impl core::convert::TryFrom<(&str,alloc::vec::Vec<alloc::boxed::Box<dyn arrow2::array::Array>>)> for polars_core::series::Series>::try_from::h985ade0f791c2562
  13:        0x10bbc6ab4 - polars_io::parquet::read_impl::column_idx_to_series::h02c849d4a0d86012
  14:        0x10bbf0104 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  15:        0x10bac7f1c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  16:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  17:        0x10bbb27ac - rayon_core::job::StackJob<L,F,R>::run_inline::h7aef4d5caab42138
  18:        0x10bac804c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  19:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  20:        0x10bac7f1c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  21:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  22:        0x10bbb20e0 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::hbfff6e380e8fcf1c
  23:        0x10c22cb7c - rayon_core::registry::WorkerThread::wait_until_cold::hb2be894f15dcf02b
  24:        0x10c044e4c - std::sys_common::backtrace::__rust_begin_short_backtrace::h3c2bb8835fc5c95e
  25:        0x10c048bf8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::haa7db99dc77153e2
  26:        0x10c0cd674 - std::sys::unix::thread::Thread::new::thread_start::h7b399846e2ac9979
  27:        0x1b33c026c - __pthread_deallocate
stack backtrace:
   0:        0x10c0ca850 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41165bc928a6a061
   1:        0x10b205a90 - core::fmt::write::hc1381c8a8889ae59
   2:        0x10c0ab838 - std::io::Write::write_fmt::h597fe54d40a99bca
   3:        0x10c0cb8e8 - std::sys_common::backtrace::print::hffd3791d3c76c5bf
   4:        0x10c0cb548 - std::panicking::default_hook::{{closure}}::hdcf127fa35c85582
   5:        0x10c0cc438 - std::panicking::rust_panic_with_hook::h1f31579a116a5567
   6:        0x10c0cbfb4 - std::panicking::begin_panic_handler::{{closure}}::h91adc5c2252dfa41
   7:        0x10c0cbf24 - std::sys_common::backtrace::__rust_end_short_backtrace::h1ce4494cc6011cab
   8:        0x10c0cbf00 - _rust_begin_unwind
   9:        0x10c1bbd34 - core::panicking::panic_fmt::he9b8054d565a504b
  10:        0x10c0ca16c - std::io::stdio::_eprint::h9187fd89875e2b57
  11:        0x10b8d491c - polars_core::series::from::<impl polars_core::series::Series>::try_from_arrow_unchecked::h8b8cea77cd903b79
  12:        0x10b8da3a0 - polars_core::series::from::<impl core::convert::TryFrom<(&str,alloc::vec::Vec<alloc::boxed::Box<dyn arrow2::array::Array>>)> for polars_core::series::Series>::try_from::h985ade0f791c2562
  13:        0x10bbc6ab4 - polars_io::parquet::read_impl::column_idx_to_series::h02c849d4a0d86012
  14:        0x10bbf0104 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  15:        0x10bac7f1c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  16:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  17:        0x10bbb20e0 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::hbfff6e380e8fcf1c
  18:        0x10c22cb7c - rayon_core::registry::WorkerThread::wait_until_cold::hb2be894f15dcf02b
  19:        0x10c044e4c - std::sys_common::backtrace::__rust_begin_short_backtrace::h3c2bb8835fc5c95e
  20:        0x10c048bf8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::haa7db99dc77153e2
  21:        0x10c0cd674 - std::sys::unix::thread::Thread::new::thread_start::h7b399846e2ac9979
  22:        0x1b33c026c - __pthread_deallocate
stack backtrace:
   0:        0x10c0ca850 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41165bc928a6a061
   1:        0x10b205a90 - core::fmt::write::hc1381c8a8889ae59
   2:        0x10c0ab838 - std::io::Write::write_fmt::h597fe54d40a99bca
   3:        0x10c0cb8e8 - std::sys_common::backtrace::print::hffd3791d3c76c5bf
   4:        0x10c0cb548 - std::panicking::default_hook::{{closure}}::hdcf127fa35c85582
   5:        0x10c0cc438 - std::panicking::rust_panic_with_hook::h1f31579a116a5567
   6:        0x10c0cbfb4 - std::panicking::begin_panic_handler::{{closure}}::h91adc5c2252dfa41
   7:        0x10c0cbf24 - std::sys_common::backtrace::__rust_end_short_backtrace::h1ce4494cc6011cab
   8:        0x10c0cbf00 - _rust_begin_unwind
   9:        0x10c1bbd34 - core::panicking::panic_fmt::he9b8054d565a504b
  10:        0x10c0ca16c - std::io::stdio::_eprint::h9187fd89875e2b57
  11:        0x10b8d491c - polars_core::series::from::<impl polars_core::series::Series>::try_from_arrow_unchecked::h8b8cea77cd903b79
  12:        0x10b8da3a0 - polars_core::series::from::<impl core::convert::TryFrom<(&str,alloc::vec::Vec<alloc::boxed::Box<dyn arrow2::array::Array>>)> for polars_core::series::Series>::try_from::h985ade0f791c2562
  13:        0x10bbc6ab4 - polars_io::parquet::read_impl::column_idx_to_series::h02c849d4a0d86012
  14:        0x10bbf0104 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  15:        0x10bbb27ac - rayon_core::job::StackJob<L,F,R>::run_inline::h7aef4d5caab42138
  16:        0x10bac804c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  17:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  18:        0x10bbb27ac - rayon_core::job::StackJob<L,F,R>::run_inline::h7aef4d5caab42138
  19:        0x10bac804c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  20:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  21:        0x10bac7f1c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  22:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  23:        0x10bac7f1c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  24:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  25:        0x10bbb20e0 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::hbfff6e380e8fcf1c
  26:        0x10c22cb7c - rayon_core::registry::WorkerThread::wait_until_cold::hb2be894f15dcf02b
  27:        0x10c044e4c - std::sys_common::backtrace::__rust_begin_short_backtrace::h3c2bb8835fc5c95e
  28:        0x10c048bf8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::haa7db99dc77153e2
  29:        0x10c0cd674 - std::sys::unix::thread::Thread::new::thread_start::h7b399846e2ac9979
  30:        0x1b33c026c - __pthread_deallocate
stack backtrace:
   0:        0x10c0ca850 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41165bc928a6a061
   1:        0x10b205a90 - core::fmt::write::hc1381c8a8889ae59
   2:        0x10c0ab838 - std::io::Write::write_fmt::h597fe54d40a99bca
   3:        0x10c0cb8e8 - std::sys_common::backtrace::print::hffd3791d3c76c5bf
   4:        0x10c0cb548 - std::panicking::default_hook::{{closure}}::hdcf127fa35c85582
   5:        0x10c0cc438 - std::panicking::rust_panic_with_hook::h1f31579a116a5567
   6:        0x10c0cbfb4 - std::panicking::begin_panic_handler::{{closure}}::h91adc5c2252dfa41
   7:        0x10c0cbf24 - std::sys_common::backtrace::__rust_end_short_backtrace::h1ce4494cc6011cab
   8:        0x10c0cbf00 - _rust_begin_unwind
   9:        0x10c1bbd34 - core::panicking::panic_fmt::he9b8054d565a504b
  10:        0x10c0ca16c - std::io::stdio::_eprint::h9187fd89875e2b57
  11:        0x10b8d491c - polars_core::series::from::<impl polars_core::series::Series>::try_from_arrow_unchecked::h8b8cea77cd903b79
  12:        0x10b8da3a0 - polars_core::series::from::<impl core::convert::TryFrom<(&str,alloc::vec::Vec<alloc::boxed::Box<dyn arrow2::array::Array>>)> for polars_core::series::Series>::try_from::h985ade0f791c2562
  13:        0x10bbc6ab4 - polars_io::parquet::read_impl::column_idx_to_series::h02c849d4a0d86012
  14:        0x10bbf0104 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  15:        0x10bbb27ac - rayon_core::job::StackJob<L,F,R>::run_inline::h7aef4d5caab42138
  16:        0x10bac804c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  17:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  18:        0x10bac7f1c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  19:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  20:        0x10bbb27ac - rayon_core::job::StackJob<L,F,R>::run_inline::h7aef4d5caab42138
  21:        0x10bac804c - rayon_core::join::join_context::{{closure}}::h7b7308fd9c993f25
  22:        0x10bbf02a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h2e36ed27afd105a1
  23:        0x10bbb20e0 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::hbfff6e380e8fcf1c
  24:        0x10c22cb7c - rayon_core::registry::WorkerThread::wait_until_cold::hb2be894f15dcf02b
  25:        0x10c044e4c - std::sys_common::backtrace::__rust_begin_short_backtrace::h3c2bb8835fc5c95e
  26:        0x10c048bf8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::haa7db99dc77153e2
  27:        0x10c0cd674 - std::sys::unix::thread::Thread::new::thread_start::h7b399846e2ac9979
  28:        0x1b33c026c - __pthread_deallocate
** (ErlangError) Erlang error: :nif_panicked
    (explorer 0.5.6) Explorer.PolarsBackend.Native.df_from_parquet("./foo.parquet", nil, nil, nil)
    (explorer 0.5.6) lib/explorer/polars_backend/data_frame.ex:183: Explorer.PolarsBackend.DataFrame.from_parquet/3
    (explorer 0.5.6) lib/explorer/data_frame.ex:546: Explorer.DataFrame.from_parquet!/2
 ```

**Comment by mlineen** [comment]
Unfortunately, I don't have enough rust programming under my belt to determine if this is a bug in pola.rs or the NIF generation.

I'm hoping by posting this, other people can confirm if they are able to replicate this finding.

I also noticed that the [NIF build is using macos-11](https://github.com/elixir-nx/explorer/blob/main/.github/workflows/release.yml#L33-L34) vs [macos-12 or macos-latest](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)

**Comment by philss** [comment]
Thanks for the details! I personally don't have an M1/M2 machine, but I guess we can test (:eyes: @josevalim / @cristineguadelupe ).
If it's only a matter of using the newest macos version, it's an easy fix.

**Comment by cigrainger** [comment]
I've got an M1 Mac. If nobody beats me to it I can test it out in a couple hours.

**Comment by josevalim** [comment]
It may be related to this: https://github.com/apollographql/rover/issues/674#issuecomment-885151934

In other words, the Erlang VM may be setting stderr to streaming mode and however is doing the error reporting is not dealing with it well.

Would it be possible to override the panic handler so it sends a message to a process, so we can use the logging facilities instead? Pinging @hansihe because he would probably know best.

**Comment by josevalim** [comment]
Good news, this consistently works on Erlang/OTP 26-rc2, which has redesigned the IO system, so I think we can consider it fixed from Erlang/OTP 26 onwards.

**Comment by hansihe** [comment]
https://github.com/rusterlium/rustler/issues/72 is the issue on the rustler issue tracker for panics due to large amounts of stdout output. Not sure if this is the same issue though.

If this specific issue happens because large panics are being printed to stdout, we could totally set a [panic hook](https://doc.rust-lang.org/std/panic/fn.set_hook.html) which sends the error to some process or something.
