### ISSUE TITLE
`Explorer.Series.cut` crashes when series is a dataframe field

### ISSUE THREAD

**Issue by petrkozorezov** [elixir-explorer/explorer#660]
explorer version is 0.6.1

```
df = Explorer.DataFrame.new(a: [0.3, 0.5, 1.1, 2.0], b: [1, 2, 3, 4])
Explorer.Series.cut(df[:a], [1.0, 2.0, 3.0])
```
```
** (ArgumentError) could not find column name "". The available entries are: ["a", "break_point", "category"]
    (explorer 0.6.1) lib/explorer/shared.ex:110: Explorer.Shared.maybe_raise_column_not_found/2
    (explorer 0.6.1) lib/explorer/data_frame.ex:3154: anonymous fn/3 in Explorer.DataFrame.rename/2
    (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer 0.6.1) lib/explorer/data_frame.ex:3153: Explorer.DataFrame.rename/2
    iex:20: (file)
```

**Comment by philss** [comment]
This is fixed by https://github.com/elixir-explorer/explorer/pull/659 and is already on main.

Thanks for reporting!
