### ISSUE TITLE
Dataframes created on a different node cannot be introspected

### ISSUE THREAD

**Issue by jasmineleonard** [elixir-explorer/explorer#768]
If a DataFrame is created on one node, attempting to introspect it on another node generates the following error:

```
Erlang error: "Could not decode field :resource on %ExDataFrame{}”
```

For example, running:

```elixir
df = Explorer.Datasets.fossil_fuels()

Node.spawn_link(:b@localhost, fn -> IO.inspect(df) end)
```

Produces the following:

```elixir
#Inspect.Error<
  got ErlangError with message:

      """
      Erlang error: "Could not decode field :resource on %ExDataFrame{}"
      """

  while inspecting:

      %{
        data: %Explorer.PolarsBackend.DataFrame{
          resource: #Reference<30177.1790930496.3019505690.34101>
        },
        names: ["year", "country", "total", "solid_fuel", "liquid_fuel", "gas_fuel",
         "cement", "gas_flaring", "per_capita", "bunker_fuels"],
        __struct__: Explorer.DataFrame,
        groups: [],
        dtypes: %{
          "bunker_fuels" => :integer,
          "cement" => :integer,
          "country" => :string,
          "gas_flaring" => :integer,
          "gas_fuel" => :integer,
          "liquid_fuel" => :integer,
          "per_capita" => {:f, 64},
          "solid_fuel" => :integer,
          "total" => :integer,
          "year" => :integer
        }
      }

  Stacktrace:

    (explorer 0.7.2) Explorer.PolarsBackend.Native.df_n_rows(%Explorer.PolarsBackend.DataFrame{resource: #Reference<30177.1790930496.3019505690.34101>})
    (explorer 0.7.2) lib/explorer/polars_backend/shared.ex:32: Explorer.PolarsBackend.Shared.apply_dataframe/3
    (explorer 0.7.2) lib/explorer/polars_backend/data_frame.ex:812: Explorer.PolarsBackend.DataFrame.inspect/2
    (explorer 0.7.2) lib/explorer/data_frame.ex:5471: Inspect.Explorer.DataFrame.inspect/2
    (elixir 1.15.7) lib/inspect/algebra.ex:348: Inspect.Algebra.to_doc/2
    (elixir 1.15.7) lib/io.ex:458: IO.inspect/3
    (elixir 1.15.7) src/elixir.erl:396: :elixir.eval_external_handler/3

>
```

Similar errors are generated for other introspection functions, eg. `print/2` and `shape/1`.

I’m not sure if this is expected behaviour, but it caught me out so may be worth documenting if so!

**Comment by josevalim** [comment]
Correct. We could probably use `node(ref) != node()` to check if it belongs to another node and raise a better error message.

**Comment by jasmineleonard** [comment]
Thanks for clarifying @josevalim!

**Comment by Jhonatannunessilva** [comment]
Is anyone already making this change?

**Comment by josevalim** [comment]
Go for it!
