### ISSUE TITLE
Series.join/2 on a summarised `list[string]` fails

### ISSUE THREAD

**Issue by cigrainger** [elixir-explorer/explorer#780]
Seems like the dataframe still thinks the list is a string col?

To reproduce:
```elixir
require Explorer.DataFrame, as: DataFrame
require Explorer.Series, as: Series
s1 = Series.from_list(["a", "a", "b", "b", "c"])
s2 = Series.from_list(["dog", "cat", "foo", "bar", "baz"])
df = %{s1: s1, s2: s2} |> DataFrame.new() |> DataFrame.group_by(:s1) |> DataFrame.summarise(s2: s2) 
```

This gives you:
```elixir
#Explorer.DataFrame<
  Polars[3 x 2]
  s1 string ["a", "b", "c"]
  s2 list[string] [["dog", "cat"], ["foo", "bar"], ["baz"]]
>
```

So far, so good. But then try:
```elixir
DataFrame.mutate(df, s2: Series.join(s2, ""))
```

```elixir
** (ArgumentError) Explorer.Series.join/2 not implemented for dtype :string. Valid dtypes are [list: :string]
    (explorer 0.7.2) lib/explorer/series.ex:5565: Explorer.Series.dtype_error/3
    #cell:um3e7nwyp2xvleq7ymf4amcsaojormuq:1: (file)
    #cell:um3e7nwyp2xvleq7ymf4amcsaojormuq:1: (file)
```

But check this out:

```elixir
[["a", "b"], [], ["c", "d", "e"]] |> Series.from_list() |> Series.join("")
```

```elixir
#Explorer.Series<
  Polars[3]
  string ["ab", "", "cde"]
>
```

Edit: I'm happy to pick this up. Just putting up as a note as I hit it when I was doing work. But if the solution jumps out at anyone please do comment with it or open a PR :).

**Comment by billylanchantin** [comment]
I started to try out a theory but immediately hit something odd in my IEx session:

```elixir
require Explorer.DataFrame, as: DataFrame
require Explorer.Series, as: Series
s1 = Series.from_list(["a", "a", "b", "b", "c"])
```

Yields:

```
#Inspect.Error<
  got FunctionClauseError with message:

      """
      no function clause matching in Explorer.PolarsBackend.Shared.apply_dataframe/3
      """

  while inspecting:

      %{
        __struct__: Explorer.Series,
        data: %Explorer.PolarsBackend.DataFrame{
          resource: #Reference<0.1528358801.207487008.66429>
        },
        dtype: :string,
        name: nil
      }

  Stacktrace:

    (explorer 0.8.0-dev) lib/explorer/polars_backend/shared.ex:31: Explorer.PolarsBackend.Shared.apply_dataframe(%{__struct__: Explorer.Series, data: %Explorer.PolarsBackend.DataFrame{resource: #Reference<0.1528358801.207487008.66429>}, dtype: :string, name: nil}, :df_n_rows, [])
    (explorer 0.8.0-dev) lib/explorer/polars_backend/data_frame.ex:862: Explorer.PolarsBackend.DataFrame.inspect/2
    (explorer 0.8.0-dev) lib/explorer/series.ex:6056: Inspect.Explorer.Series.inspect/2
    (elixir 1.14.3) lib/inspect/algebra.ex:341: Inspect.Algebra.to_doc/2
    (elixir 1.14.3) lib/kernel.ex:2254: Kernel.inspect/2
    (iex 1.14.3) lib/iex/evaluator.ex:373: IEx.Evaluator.io_inspect/1
    (iex 1.14.3) lib/iex/evaluator.ex:332: IEx.Evaluator.eval_and_inspect/3
    (iex 1.14.3) lib/iex/evaluator.ex:303: IEx.Evaluator.eval_and_inspect_parsed/3

>
```

I'm on `main`.

**Comment by billylanchantin** [comment]
(Sorry for all the spam!)

This works for me on `main`:

```elixir
require Explorer.DataFrame, as: DataFrame
require Explorer.Series, as: Series
s1 = Series.from_list(["a", "a", "b", "b", "c"])
s2 = Series.from_list(["dog", "cat", "foo", "bar", "baz"])
df = %{s1: s1, s2: s2} |> DataFrame.new() |> DataFrame.group_by(:s1) |> DataFrame.summarise(s2: s2)
# Don't forget the new col name!
DataFrame.mutate(df, s3: Series.join(s2, ""))
```

```                                                  
#Explorer.DataFrame<
  Polars[3 x 3]
  s1 string ["a", "b", "c"]
  s2 list[string] [["dog", "cat"], ["foo", "bar"], ["baz"]]
  s3 string ["dogcat", "foobar", "baz"]
>
```

I think whatever is going on was addressed between the release and now.

**Comment by cigrainger** [comment]
Thanks @billylanchantin! I think requiring a new column name is a bug. We should be able to mutate in place.

**Comment by josevalim** [comment]
I think it all works on main:

```
iex(6)> Series.join(df["s2"], "")
#Explorer.Series<
  Polars[3]
  string ["dogcat", "foobar", "baz"]
>
```

This works:

```
iex(7)> DataFrame.mutate(df, s2: Series.join(s2, ""))
#Explorer.DataFrame<
  Polars[3 x 2]
  s1 string ["a", "b", "c"]
  s2 string ["dogcat", "foobar", "baz"]
>
```

Your syntax does not work but it is not meant to work:

```
iex(8)> DataFrame.mutate(df, Series.join(s2, ""))
** (Protocol.UndefinedError) protocol Enumerable not implemented for #Explorer.Series<
  LazySeries[???]
  string (join(column("s2"), ""))
> of type Explorer.Series (a struct).
```

If this is common, we can probably check and raise a better error message.

**Comment by billylanchantin** [comment]
> If this is common, we can probably check and raise a better error message.

👍 

I've gotten that error a lot. I'm used to it now, but I think something more informative would be better. Something like:

```
** (ArgumentError) 2nd argument for `mutate` must be a keyword list.

  `mutate` expects a keyword list where:

    * the keys are column names (old or new) and
    * the values are expressions.

  Example:

    iex> require Explorer.DataFrame
    iex> df = Explorer.DataFrame.new(a: [1, 2, 3])
    iex> Explorer.DataFrame.mutate(df, b: 2 * a)
```

**Comment by josevalim** [comment]
:+1: for restricting it to keyword lists. We can start by  adding a is_list guard.

**Comment by cigrainger** [comment]
Oh... I'm sorry guys. That was a copy/paste issue. When I said mutate in place, I assumed that I had given you the correct code above, which is `DataFrame.mutate(s2: Series.join(s2, "")`. I've corrected the code above now and can repro reliably on 0.7.2. You have to go through all the steps -- I think the bug is to do with the summarise before the mutate. 

But it's fixed on main. So I'm closing this. 😊
