### ISSUE TITLE
`from_ndjson` does not load column with nulls and results in `MatchError`

### ISSUE THREAD

**Issue by lkarthee** [elixir-explorer/explorer#783]
Example 1:
```json
{"col_a":null,"col_b":5.1}
{"col_a":null,"col_b":5.2}
```
Example 2:
```json
{"col_a":1,"col_b":5.1}
{"col_a":null,"col_b":5.2}
```
### Python
In python both examples work.

```python
import polars as pl
test_df = pl.read_ndjson("test.ndjson")
```
```
shape: (2, 2)
┌───────┬───────┐
│ col_a ┆ col_b │
│ ---   ┆ ---   │
│ null  ┆ f64   │
╞═══════╪═══════╡
│ null  ┆ 5.1   │
│ null  ┆ 5.2   │
└───────┴───────┘
```

### Elixir
```elixir
path = Path.dirname(__ENV__.file)
Explorer.DataFrame.from_ndjson!("#{path}/test.ndjson")
```
1st example results in match error. 

```
** (MatchError) no match of right hand side value: {:error, "Generic Error: cannot cast to dtype: null"}
    (explorer 0.7.2) lib/explorer/polars_backend/shared.ex:101: Explorer.PolarsBackend.Shared.df_dtypes/1
    (explorer 0.7.2) lib/explorer/polars_backend/shared.ex:87: Explorer.PolarsBackend.Shared.create_dataframe/1
    (explorer 0.7.2) lib/explorer/polars_backend/data_frame.ex:238: Explorer.PolarsBackend.DataFrame.from_ndjson/3
    (explorer 0.7.2) lib/explorer/data_frame.ex:1432: Explorer.DataFrame.from_ndjson!/2
    test.livemd#cell:m2xee4iyla3uzqzqyvkp6ibty3pdsg7d:3: (file)
```

Only 2nd example works.

```elixir
#Explorer.DataFrame<
  Polars[2 x 2]
  col_a string [nil, nil]
  col_b f64 [5.1, 5.2]
>
```

This behaviour is inconsistent, as this is a `MatchError` in framework code. 

### Dependencies:
```elixir
Mix.install([
  {:explorer, "~> 0.7.0"},
  {:kino, "~> 0.10.0"},
])
```

**Comment by billylanchantin** [comment]
Thanks for the report! This does appear to be a bug.

I've recreated the issue in tests:

```elixir
# In: test/explorer/data_frame/ndjson_test.exs
  describe "nulls" do
    # Runs fine.
    test "column with a null and a non-null" do
      DF.new(a: [nil, 1])
      |> tmp_ndjson_file!()
      |> DF.from_ndjson!()
    end

    # Raises with:
    # ** (MatchError) no match of right hand side value: {:error, "Generic Error: cannot cast to dtype: null"}
    test "column with only nulls" do
      DF.new(a: [nil, nil])
      |> tmp_ndjson_file!()
      |> DF.from_ndjson!()
    end
  end
```

**Comment by josevalim** [comment]
@billylanchantin this may be a Polars thing. They do not want to guess what is the column type if you only have nils, so you need to explicitly provide the type or exclude the column.

**Comment by josevalim** [comment]
It seems arrow has a null dtype, so we need to support it: https://arrow.apache.org/docs/python/api/datatypes.html

**Comment by lkarthee** [comment]
Looks like even example is bug in polars library  - https://github.com/pola-rs/polars/issues/13183 . No action required in explorer.

**Comment by josevalim** [comment]
Good find. Only example1 then.

**Comment by lkarthee** [comment]
This issue can be closed combo of  :null PRs and upgrade to polars v0.36.2 fixed the issue.
