### ISSUE TITLE
Seeing `:nif_not_loaded` error for `Series.split/2` when mutating a dataframe

### ISSUE THREAD

**Issue by H12** [elixir-explorer/explorer#874]
When I run the following:

```elixir
Mix.install([explorer: "~> 0.8.1"])
df = Explorer.DataFrame.new(a: ["foo,bar", "bar,baz"])
Explorer.DataFrame.mutate(df, b: split(a, ","))
```

I see this error:
```
** (ErlangError) Erlang error: :nif_not_loaded
    :erlang.nif_error(:nif_not_loaded)
    (explorer 0.8.1) lib/explorer/polars_backend/native.ex:458: Explorer.PolarsBackend.Native.err/0
    (explorer 0.8.1) lib/explorer/polars_backend/data_frame.ex:625: anonymous fn/2 in Explorer.PolarsBackend.DataFrame.mutate_with/3
    (elixir 1.16.1) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer 0.8.1) lib/explorer/polars_backend/data_frame.ex:623: Explorer.PolarsBackend.DataFrame.mutate_with/3
    iex:6: (file)
```

Referencing #718, it looks like this is another issue of a missing native expression -- I can try to put up a PR to add one 🙂

**Comment by billylanchantin** [comment]
Ah yep! That's exactly what that is. And thank you, a PR would be welcome :)
